### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by DiBeck** [olavolav/te-causality#9]
Dear all, 

i hope one of you can help me with a compilation Problem. I running into a problem during the compilation with  ```rake all --trace ``` . I have installed the dependencies, SimKernel, Boost, GSL, yaml_cpp. 

The shown output is the following. And it seems that the compiler does not recognize the .o files. Do I have to install something in order to read this files? This problem occurred on a Ubuntu 14.10 OS. 
```
** Invoke all (first_time)
** Invoke xcorr (first_time)
** Invoke obj (first_time)
** Invoke ./maketemp/olav.o (first_time, not_needed)
** Invoke ../olav.cpp (first_time, not_needed)
** Invoke ./maketemp/te-datainit.o (first_time, not_needed)
** Invoke ../te-datainit.cpp (first_time, not_needed)
** Invoke ./maketemp/miniprofiler.o (first_time, not_needed)
** Invoke ../miniprofiler.cpp (first_time, not_needed)
** Execute obj
** Invoke ./maketemp/xcorr.o (first_time, not_needed)
** Invoke xcorr.cpp (first_time, not_needed)
** Execute xcorr
g++ -O3 ./maketemp/olav.o ./maketemp/te-datainit.o ./maketemp/miniprofiler.o ./maketemp/xcorr.o -o xcorr -lgsl -lgslcblas -lm -lyaml-cpp -L. -lsim
./maketemp/olav.o: file not recognized: Dateiformat nicht erkannt
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [g++ -O3 ./maketemp/olav.o ./maketemp/te-da...]
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:54:in `block in create_shell_runner'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:45:in `call'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:45:in `sh'
/usr/lib/ruby/vendor_ruby/rake/file_utils_ext.rb:37:in `sh'
/home/dirk/Projekte/te-causality-master/te-causality-master/transferentropy-sim/Rakefile:52:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:236:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:236:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:231:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:231:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:168:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:197:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:195:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:195:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:168:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:161:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:149:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:165:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => all => xcorr
```

Thanks for the help

Dirk

**Comment by orlandi** [comment]
Weird...
Did you compile any of the dependencies by hand?
I just tried on a fresh 14.10 install and found no issues after installing only these packages through apt-get:
`make rake gcc g++ git libboost-dev libgsl0-dev libyaml-cpp-dev libflann-dev`

Did you compile simkernel on a different machine maybe?
You could check the library file format with:

    objdump -a /usr/local/lib/libsim.a 

(if you installed simkernel through a sudo make install). It should coincide with the output from `objdump -a maketemp/*.o`.

Also make sure you do not have any other compilation of simkernel in your path.

**Comment by DiBeck** [comment]
I had not installed git, and must have changed something in the olav.o file. After i downloaded the soucecode again the compiling worked.

**Comment by olavolav** [comment]
Cool, glad to hear it works now.
